### ISSUE TITLE
Completed task syntax not working

### ISSUE THREAD

**Issue by solloron1** [samwho/todo-txt-gem#40]
When reading through a file that has a few tasks I have one with 'x ' and when checking to see if it is done it displays as false when it should be true.

**Comment by maetl** [comment]
Thanks. This is possibly to do with following the todo.txt spec, where done tasks require a date.

See the test cases here: https://github.com/samwho/todo-txt-gem/blob/master/spec/todo-txt/task_spec.rb#L146

To switch off the `completed_on` date and allow any line with a leading `x` to be completed, you can use the following option:

```ruby
Todo.customize do |options|
  options.require_completed_on = false
end
```

**Comment by solloron1** [comment]
Thanks for the quick reply! And I was just reviewing my code. I'm the one causing the syntax issues. I had an == instead of =. 

I do have another quick question. How do you use the methods in the Syntax module?

**Comment by maetl** [comment]
The Syntax module isn’t really designed for standalone use but given the way it’s put together, it should be able to be used directly. Because all the parsing helpers area instance methods, the module needs to be embedded in another scope to work:

```ruby
class MyParser
  include Todo:: Syntax
end
```

See examples here: https://github.com/samwho/todo-txt-gem/blob/master/spec/todo-txt/syntax_spec.rb

**Comment by solloron1** [comment]
Thanks for the responses! You've answered my questions and I'll be closing this.
