### ISSUE TITLE
Add support for saving a todo.txt file

### ISSUE THREAD

**Issue by samwho** [samwho/todo-txt-gem#5]
Currently this library is read only, despite having functions to mark tasks as completed and whatnot. It would be excellent if support were added to write back to the todo.txt file.

Something akin to this:

``` ruby
require 'todo-txt'

list = Todo::List.new("path/to/todo.txt")
list << Todo::Task.new("(A) This is a new task!")
list.save!
```

**Comment by lorentrogers** [comment]
I've been fiddling with this library over on my pet-project, and I've come up with some basic file handling. https://github.com/lorentrogers/todo-curses/blob/dev/lib/TodoCurses/todo_file.rb I copied out the files from this gem just to get a feel for them in my app and to get working on it quickly. I plan on pulling out my changes and  submitting them as a PR here. 

I split file handling into a new class, because the `List` class makes multiple copies of itself for the filters. When you get a `List` object, there's no guarantee that it'll have a file path. Instead, the `TodoList` object should always have a path associated with it. This can be used to generate filtered `List` objects as needed.

I also split out all of the examples in the comments into test suites. (Under `todo-curses/test`.) I'll make another PR for those.
